provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  insert-user:
    lang: node8-express
    handler: ./insert-user
    image: ryanzebian/insert-user
    environment:
      write_timeout: 10s
      read_timeout: 10s
      mongo: openfaas-db-mongodb
  find-users:
    lang: node8-express
    handler: ./find-users
    image: ryanzebian/find-users
    environment:
      write_timeout: 10s
      read_timeout: 10s
      mongo: openfaas-db-mongodb